### ISSUE TITLE
SYSTEM/OPTIONS/PATH value

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#7]
Currently `system/options/path` is `_`. I think it should be `/path/to/current/page`.

**Comment by hostilefork** [comment]
One question to ask is how this relates to the "fake filesystem" option in emscripten.

It seems like the fake filesystem would be more trouble than its worth for static resources used by your page...you'd have to rebuild the %libr3.js to change it.  But if you're looking for a way to have persistence in your site between sessions, the local file storage might be a nice API for doing that.  I was thinking in the tutorial this could be storing information about your progress--for instance.

So if that's going to be a thing, then I think at minimum it means that the `system/options/path` should be a full URL, to distinguish it from an actual FILE! in the local file storage.

*(Another thing to ask is how much the Javascript extension tries to sense the environment...if it is running under Node, or on a web worker, or in a browser...and where that code is.  We can put more code in the extension, that includes default behaviors for PRINT and such.)*

**Comment by hostilefork** [comment]
I added code which sets SYSTEM/OPTIONS/PATH, and also uses CHANGE-DIR so Rebol knows where it is script relative, it [runs in %gui.js](https://github.com/hostilefork/replpad-js/blob/91e84813e4e5359564b1edaf2ace2303c5d23b53/gui.js#L767).  This way WHAT-DIR starts out having a good answer.  JS-DO and CSS-DO use WHAT-DIR so that you can DO a script at a URL and then that script can do something like **css-do %css/something.css** and it knows it means relative to the URL of the script you are doing.

For an example, try **`do https://gitlab.com/hostilefork/popupdemo/raw/master/popupdemo.reb`** you will notice that its css and jss are loading relative to that, not relative to the replpad:

https://gitlab.com/hostilefork/popupdemo/blob/d563aad0357f34a5a92a443353166da15ef04097/popupdemo.reb#L12

*(Note also it uses /automime, and that the raw URLs are automatically translated to API calls for GitLab!)*
