### ISSUE TITLE
now/time/precise without decimal digits in Firefox 84.0.1

### ISSUE THREAD

**Issue by MarkoSchuetz** [hostilefork/replpad-js#82]
In the wasn REPL
```
>> now/time/precise
== 15:29:17
```
in the compiled command-line REPL
```
>> now/time/precise
== 15:32:35.776514
```

**Comment by hostilefork** [comment]
Updated...note that browsers only give millisecond precision.

Since you are handy with C (!) then the details of the commits should hopefully give you a lens for grasping how the system tries to work:

**C changes**
https://github.com/metaeducation/ren-c/commit/808c70d79ab142ac624b8185b686e37e7ce3de3f

**ReplPad changes**
https://github.com/hostilefork/replpad-js/commit/d4f8822c661e1cc38ed9ebeb535270e7b6371344

The C comment block with the specification for the **native** prototype is gathered by the build process, and embedded into the executable to be LOADed at boot time...and then coupled with the C function pointer to make a native function.

Function frames are just ordered arrays of cells, addressed by integer index.  The names read out of the comment block are used to create the macros like **INCLUDE_PARAMS_OF_MAKE_TIME_SN**.  They merely expand to constants telling what that order is:

    #define PARAM(n,name) \
        static const int p_##name##_ = n

    #define INCLUDE_PARAMS_OF_MAKE_TIME_SN \
        PARAM(1, return); \
        USED(ARG(return)); \
        PARAM(2, seconds); \
        PARAM(3, nano); \
        assert(GET_SERIES_INFO(frame_->varlist, HOLD))

Then, the C function body can access the parameter by the name...but being looked up just by that constant index:

    #define ARG(name) \
        FRM_ARG(frame_, (p_##name##_))

The goal is to keep this foundation simple...while pushing the boundaries of what can be done with the approach.
